services:
  step-ca-unbound:
    container_name: step-ca-unbound
    image: ghcr.io/zyrakq/unbound:latest
    ports:
      - "${DNS_SERVER}:53:53/udp"
      - "${DNS_SERVER}:53:53/tcp"
    environment:
      ACCESS_CONTROL_CUSTOM: ${ACCESS_CONTROL_CUSTOM}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}
      BLOCK_PRIVATE: ${BLOCK_PRIVATE:-false}
    restart: unless-stopped