services:
  step-ca:
    container_name: step-ca
    image: smallstep/step-ca:latest
    environment:
      - DOCKER_STEPCA_INIT_NAME=Step CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=step-ca,localhost
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
    volumes:
      - step-ca-data:/home/step
    networks:
      - step-ca-proxy-tier
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "step", "ca", "health", "--ca-url=https://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  step-ca-proxy:
    container_name: step-ca-proxy
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - step-ca-vhost:/etc/nginx/vhost.d
      - step-ca-certs:/etc/nginx/certs:ro
      - step-ca-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - step-ca-proxy-tier
      - step-ca-network

  step-ca-companion:
    container_name: step-ca-companion
    image: ghcr.io/zyrakq/step-ca-companion:latest
    # build:
    #   context: ./src/step-ca-companion/app
    #   dockerfile: Dockerfile
    environment:
      ACME_CA_URI: https://step-ca:9000/acme/acme/directory
      ACME_STAGING: false
      STEP_CA_CONTAINER_NAME: step-ca
      STEP_CA_BOOTSTRAP_TIMEOUT: 300
    restart: always
    depends_on:
      step-ca:
        condition: service_healthy
      step-ca-proxy:
        condition: service_started
    volumes:
      - step-ca-acme:/etc/acme.sh
      - step-ca-vhost:/etc/nginx/vhost.d
      - step-ca-certs:/etc/nginx/certs
      - step-ca-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - step-ca-proxy-tier

volumes:
  step-ca-data:
    name: step-ca-data
  step-ca-acme:
    name: step-ca-acme
  step-ca-vhost:
    name: step-ca-vhost
  step-ca-certs:
    name: step-ca-certs
  step-ca-html:
    name: step-ca-html

networks:
  step-ca-proxy-tier:
    name: step-ca-proxy-tier
    driver: bridge
  step-ca-network:
    name: step-ca-network
    driver: bridge