services:
  step-ca-unbound:
    container_name: step-ca-unbound
    image: ghcr.io/zyrakq/unbound:latest
    restart: unless-stopped
    environment:
      ACCESS_CONTROL_CUSTOM: ${ACCESS_CONTROL_CUSTOM}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}
      BLOCK_PRIVATE: ${BLOCK_PRIVATE:-false}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "${DNS_SERVER}:53:53/udp"
      - "${DNS_SERVER}:53:53/tcp"